include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - lint
  - test
  - build

gdscriptlint:
  image: python:3
  stage: lint
  before_script:
    - pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git
  script:
    - gdlint addons
    - gdlint examples

markdownlint:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run markdownlint
    - npm run changeloglint

prettier:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run prettier:test

spellcheck:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run spellcheck

sast:
  stage: test

build:
  stage: build
  parallel:
    matrix:
      - GODOT: ["4.3", "4.4"]
  script: curl --request POST --form token=${CI_JOB_TOKEN} --form ref="godot/${GODOT}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
  rules:
    - if: $CI_COMMIT_TAG

package:
  stage: build
  image: node:latest
  before_script:
    - apt-get clean
    - apt-get -yqq update
    - apt-get -yqqf install zip rsync
  script:
    - PACKAGE_NAME=$(grep '"name":' package.json -m1 | cut -d\" -f4)
    - PACKAGE_VERSION=$(grep '"version":' package.json -m1 | cut -d\" -f4)
    - mkdir -p dist/${PACKAGE_NAME}
    - rsync -av ./addons dist/${PACKAGE_NAME}/
    - cd dist
    - zip -r ${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip .
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${PACKAGE_VERSION}/${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'api' && $CI_COMMIT_BRANCH == /^godot\/.*$/
