include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - lint
  - test
  - release

variables:
  PACKAGE_NAME: "resonate"
  PACKAGE_VERSION: "2.4.1"

gdscriptlint:
  image: python:3
  stage: lint
  before_script:
    - pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git
  script:
    - gdlint addons
    - gdlint examples

markdownlint:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run markdownlint
    - npm run changeloglint

prettier:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run prettier:test

spellcheck:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run spellcheck

sast:
  stage: test

release:
  stage: release
  image: gitlab/glab:latest
  script:
    - glab auth login --job-token ${CI_JOB_TOKEN}
    - glab release create ${PACKAGE_VERSION}
  rules:
    - if: $CI_COMMIT_TAG

build:
  stage: release
  needs:
    - job: release
  parallel:
    matrix:
      - GODOT: ["4.3", "4.4"]
  script: curl --request POST --form token=${CI_JOB_TOKEN} --form ref="godot/${GODOT}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
  rules:
    - if: $CI_COMMIT_TAG

package:
  stage: release
  image: gitlab/glab:latest
  before_script:
    - apk add zip rsync
  script:
    - mkdir -p dist/${PACKAGE_NAME}
    - rsync -av ./addons dist/${PACKAGE_NAME}/
    - cd dist
    - zip -r ${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip .
    - glab auth login --token ${RESONATE_TOKEN}
    - glab release upload ${PACKAGE_VERSION} dist/${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip
  artifacts:
    paths:
      - dist/${PACKAGE_NAME}-${PACKAGE_VERSION}-${CI_COMMIT_REF_SLUG}.zip
    expire_in: never
  rules:
    - if: $CI_PIPELINE_SOURCE == 'pipeline'
